services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - app_network

  php:
    image: php:${PHP_VERSION}-fpm
    container_name: my_php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network

  php-cli:
    image: php:${PHP_VERSION}-cli
    container_name: my_php_cli
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    entrypoint: tail -f /dev/null  # Keeps the container running
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
